### ISSUE TITLE
Q-Chem input generator

### ISSUE THREAD

**Issue by berquist** [cyllab/ccinput#3]
Hi! I saw you had this as a lower-priority item on your project board, and it isn't on the GSoC ideas list with NWChem, so I figured I'd start one. The core is in place and I've translated about 2/3rds of the ORCA tests. Pretty much every ORCA test can be supported, though there is freezing string (FSM) instead of NEB, and I'll probably skip geometry constraints for now.

Even though it's lower priority, are there any particular features (aside from RI and solvation) that you'd like to see supported? Is there a preferred input file "style"?

**Comment by RaphaelRobidas** [comment]
Thank you for your work! I don't use Q-Chem myself, so you can decide how to handle the input file style. As for the feature, the most important ones in my opinion are the ones covering 95% of use cases: opt, freq, sp, optts and eventually constrained optimisations, with at least DFT support.

One particular thing that would be helpful is starting to add the specific Q-Chem keywords and other static data in `ccinput/constants.py` (namely `SOFTWARE_METHODS`, `SOFTWARE_BASIS_SETS`, `SOFTWARE_SOLVENTS`). If there are new solvents, methods or basis sets that are not built in Gaussian or ORCA, they should be added to `SYN_SOLVENTS`, `SYN_METHODS` or `SYN_BASIS_SETS`. It's a bit tedious, but hopefully most options exist already and you simply have to indicate that they are available in Q-Chem.

Looking forward to seeing this addition!
