### ISSUE TITLE
Counterpoise correction calculations Gaussian

### ISSUE THREAD

**Issue by zarkoivkovicc** [cyllab/ccinput#4]
The counterpoise correction calculations using the counterpoise keyword could be added to Gaussian input files.
It's not a simple keyword as it requires modification of the coordinate part of the file. I guess that's why it's not already implemented.
I think the feature could be handy and as this is not part of GSoC, could I try to implement it?

**Comment by RaphaelRobidas** [comment]
Sure, go ahead! That would be a nice addition indeed. In fact, the way you handle the fragments could also be used in an eventual implementation of ONIOM calculations.
